### ISSUE TITLE
Use compression for more data per message

### ISSUE THREAD

**Issue by TheAlan404** [aleixrodriala/wa-tunnel#7]
We can make compression optional using some sort of configuration like `config.json`

good ol' [`require("zlib")`](https://nodejs.org/api/zlib.html#zlib) can do

**Comment by aleixrodriala** [comment]
Sure, we can set it as optional if we find any efficient one.

I tested though using brotli for example and got same character length or sometimes a bit more since you still have to encode it to base64 or to String after compressing.

But I still have to do more testing with gzip or other compression methods to be able to have a better compression rate than only base64.

If anyone knows a more efficient method please let me know.

**Comment by aleixrodriala** [comment]
Yes, the issue with files is the latency, that's why I added it in the todo list only for sending big chunks.

Another thing that we would need to do is cache socket answers since most of the times give partial answers and by doing so we also could reduce some latency.

**Comment by aleixrodriala** [comment]
Working on files version in the branch assigned

**Comment by aleixrodriala** [comment]
Fixed by #10
